/*________________TABLES________________*/
-- Create PRODUCT table
CREATE TABLE PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    DESCRIPTION VARCHAR(255)
);

-- Create CUSTOMER table
CREATE TABLE CUSTOMER (
    CUST_ID INT PRIMARY KEY,
    CUST_NAME VARCHAR(100),
    ADDRESS VARCHAR(255)
);

-- Create CUSTOMER_SALE table
CREATE TABLE CUSTOMER_SALE (
    SALES_ID INT PRIMARY KEY,
    CUST_ID INT,
    SALE_DATE DATE,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID)
);

-- Create SALE_ITEM table (Associative table)
CREATE TABLE SALE_ITEM (
    SALES_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    PRIMARY KEY (SALES_ID, PRODUCT_ID),
    FOREIGN KEY (SALES_ID) REFERENCES CUSTOMER_SALE(SALES_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- Create PET_CARE_LOG table with auditing columns
CREATE TABLE PET_CARE_LOG (
    PRODUCT_ID INT,
    LOG_DATETIME TIMESTAMP,
    COMMENTS VARCHAR(4000),
    UPDATE_DATE TIMESTAMP,
    UPDATED_BY_USER VARCHAR(100),
    PRIMARY KEY (PRODUCT_ID, LOG_DATETIME),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);



/*________________QUERIES & TRIGGERS________________*/
-- Trigger before INSERT
CREATE OR REPLACE TRIGGER TRG_PET_CARE_LOG_INSERT
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.UPDATE_DATE := SYSDATE;
    :NEW.UPDATED_BY_USER := USER;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'An error occurred during insert: ' || SQLERRM);
END;



-- Trigger before UPDATE
CREATE OR REPLACE TRIGGER TRG_PET_CARE_LOG_UPDATE
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != :OLD.UPDATED_BY_USER THEN
        RAISE_APPLICATION_ERROR(-20002, 'Update failed: You can only update records you created.');
    END IF;
    
    :NEW.UPDATE_DATE := SYSDATE;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -20002 THEN
            RAISE;
        ELSE
            RAISE_APPLICATION_ERROR(-20003, 'An error occurred during update: ' || SQLERRM);
        END IF;
END;


-- Trigger before DELETE
CREATE OR REPLACE TRIGGER TRG_PET_CARE_LOG_DELETE
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != 'JOEMANAGER' THEN
        RAISE_APPLICATION_ERROR(-20004, 'Delete failed: Only JOEMANAGER is authorized to delete logs.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -20004 THEN
            RAISE;
        ELSE
            RAISE_APPLICATION_ERROR(-20005, 'An error occurred during delete: ' || SQLERRM);
        END IF;
END;